#!/usr/bin/env python
__ts__ = "Last edited: <2022-03-14 09:08:06 wcobb>"

import threat.common
import threat.platform
import threat.core

'''
Some common utilities for the bp package


'''

def get_version(ts:str = __ts__) -> str:
    '''
    A function that accepts a time-stamp string generated by Emacs, namely:

    "Time-stamp: <%Y-%m-%d %H:%M:%S Author>"

    ... and then returns a version string of the form...

    "%y.%m%d.%H%M%S"

    where the "%" expressions are standard notations for the unix date command.


    '''
    print(ts)
    [junk1, date_string, time_string, junk2] = ts.split(" ")
    date_parts = date_string.replace('<20','').split('-')
    time_parts = time_string.split(':')
    version = ("%2s.%2s%2s.%2s%2s%2s" %
                   (date_parts[0], date_parts[1], date_parts[2],
                    time_parts[0], time_parts[1], time_parts[2]))
    return version


if (__name__ == "__main__"):
    '''

    '''
    import threat
    print(threat.get_version())
    



